PROJECT_ID ?=
REGION ?= us-central1
ARTIFACT_REPOSITORY ?= kibitz
CLOUD_RUN_REGION ?= $(REGION)
DB_REGION ?= $(REGION)
IMAGE_TAG ?= $(shell git rev-parse --short HEAD)-$(shell date +%s)
TF_STATE_BUCKET ?=

.PHONY: deploy
deploy:
	@PROJECT_ID=$(PROJECT_ID) REGION=$(REGION) CLOUD_RUN_REGION=$(CLOUD_RUN_REGION) \
	ARTIFACT_REPOSITORY=$(ARTIFACT_REPOSITORY) DB_REGION=$(DB_REGION) IMAGE_TAG=$(IMAGE_TAG) \
	TF_STATE_BUCKET=$(TF_STATE_BUCKET) \
	bash scripts/deploy.sh
